In [1]:
import os
import glob
import gc
import pandas as pd

In [5]:
path = r'C:\8ssible-Healing-Seoul-Analysis\branch_SG\8SSIBLE_SG_DATA\쓰레기수거+현황(2020년+이후)_20260422193426.csv'

df_raw = pd.read_csv(path, encoding='utf-8-sig')

# 첫 2행은 헤더 정보, 2행부터 실제 데이터
df_trash = df_raw.iloc[2:].copy()

# 컬럼명 만들기
new_cols = ['구분1', '자치구']

for col, upper, lower in zip(df_raw.columns[2:], df_raw.iloc[0, 2:], df_raw.iloc[1, 2:]):
    year = col.split('.')[0]
    new_cols.append(f'{year}_{upper}_{lower}')

df_trash.columns = new_cols

# 인덱스 정리
df_trash = df_trash.reset_index(drop=True)

df_trash.head()

,구분1,자치구,2022_행정구역(A)_면적 (km²),2022_행정구역(A)_인구 (명),2022_청소구역(B)_면적 (km²),2022_청소구역(B)_인구 (명),2022_처리방법 (톤/년)_소계,2022_처리방법 (톤/년)_매립,2022_처리방법 (톤/년)_소각,2023_행정구역(A)_면적 (km²),...,2023_처리방법 (톤/년)_소계,2023_처리방법 (톤/년)_매립,2023_처리방법 (톤/년)_소각,2024_행정구역(A)_면적 (km²),2024_행정구역(A)_인구 (명),2024_청소구역(B)_면적 (km²),2024_청소구역(B)_인구 (명),2024_처리방법 (톤/년)_소계,2024_처리방법 (톤/년)_매립,2024_처리방법 (톤/년)_소각
0,합계,소계,605.21,9667669,605.21,9667669,15904316.280209,431348.39853,971704.040044,605.2,...,13741210.042016,343719.49013,1032402.62713,605.25,9597372,605.25,9597372,14095481.315299,287640.66289,1049468.662
1,합계,종로구,23.91,152211,23.91,152211,388016.679124,7125.5,41873.419394,23.91,...,326233.012008,6172.5,40532.252066,23.91,149608,23.91,149608,280517.950779,4060.71,40085.742
2,합계,중구,9.96,130785,9.96,130785,441835.866543,8793.06,45657.150932,9.96,...,349138.475363,6945.73,47048.865188,9.96,131214,9.96,131214,463201.226735,4812.948,43340.32
3,합계,용산구,21.87,233284,21.87,233284,949707.090543,6981.03,34096.456543,21.87,...,861823.613264,5123.66,34370.316264,21.87,217194,21.87,217194,424046.90021,3751.57,33854.66
4,합계,성동구,16.82,288234,16.82,288234,1087033.776017,33898.4,29292.226487,16.82,...,950480.916244,12525.1,37245.025761,16.86,281289,16.86,281289,1027416.049541,6383.06,35877.64

In [8]:
df_trash = df_trash.drop(columns = '구분1')

In [9]:
df_trash

,자치구,2022_행정구역(A)_면적 (km²),2022_행정구역(A)_인구 (명),2022_청소구역(B)_면적 (km²),2022_청소구역(B)_인구 (명),2022_처리방법 (톤/년)_소계,2022_처리방법 (톤/년)_매립,2022_처리방법 (톤/년)_소각,2023_행정구역(A)_면적 (km²),2023_행정구역(A)_인구 (명),...,2023_처리방법 (톤/년)_소계,2023_처리방법 (톤/년)_매립,2023_처리방법 (톤/년)_소각,2024_행정구역(A)_면적 (km²),2024_행정구역(A)_인구 (명),2024_청소구역(B)_면적 (km²),2024_청소구역(B)_인구 (명),2024_처리방법 (톤/년)_소계,2024_처리방법 (톤/년)_매립,2024_처리방법 (톤/년)_소각
0,소계,605.21,9667669,605.21,9667669,15904316.280209,431348.39853,971704.040044,605.2,9638799,...,13741210.042016,343719.49013,1032402.62713,605.25,9597372,605.25,9597372,14095481.315299,287640.66289,1049468.662
1,종로구,23.91,152211,23.91,152211,388016.679124,7125.5,41873.419394,23.91,150453,...,326233.012008,6172.5,40532.252066,23.91,149608,23.91,149608,280517.950779,4060.71,40085.742
2,중구,9.96,130785,9.96,130785,441835.866543,8793.06,45657.150932,9.96,131793,...,349138.475363,6945.73,47048.865188,9.96,131214,9.96,131214,463201.226735,4812.948,43340.32
3,용산구,21.87,233284,21.87,233284,949707.090543,6981.03,34096.456543,21.87,227106,...,861823.613264,5123.66,34370.316264,21.87,217194,21.87,217194,424046.90021,3751.57,33854.66
4,성동구,16.82,288234,16.82,288234,1087033.776017,33898.4,29292.226487,16.82,284766,...,950480.916244,12525.1,37245.025761,16.86,281289,16.86,281289,1027416.049541,6383.06,35877.64
5,광진구,17.06,351252,17.06,351252,348781.212735,8973.98,18398.527835,17.06,351180,...,222019.36777,8239.02,30846.40797,17.06,348652,17.06,348652,266067.70253,8265.22,29985.77
6,동대문구,14.22,353601,14.22,353601,542008.61394,9662.97,34933.89893,14.22,359873,...,325180.678875,7427.3,36531.916535,14.22,358603,14.22,358603,341849.804305,4863.55,37377.8
7,중랑구,18.5,390140,18.5,390140,318052.861645,7474.52015,34832.676955,18.5,387470,...,204165.710741,4509.22,36620.573321,18.5,385349,18.5,385349,320190.993226,3062.37,38750.62
8,성북구,24.58,441984,24.58,441984,587313.965747,3314.41,32555.541387,24.58,438168,...,319193.894016,1557.66013,41316.006386,24.57,435037,24.57,435037,363601.155563,2222.56,30493.71
9,강북구,23.6,297702,23.6,297702,271452.586542,2381.98,25818.712843,23.6,292977,...,213455.88551,2336.37,25244.013,23.6,289374,23.6,289374,249110.901319,2312.21,24908.4
10,도봉구,20.65,313989,20.65,313989,277653.038835,2787.79,20919.996075,20.65,309494,...,199962.568521,3168.68,37931.293021,20.65,306032,20.65,306032,552721.21333,2198.05,21056.82
11,노원구,35.44,508014,35.44,508014,563441.299553,29106.58,37402.855353,35.44,502925,...,488241.238086,30564.25,35593.453466,35.44,496552,35.44,496552,363002.939988,27323.731,43500.86
12,은평구,29.71,470602,29.71,470602,481162.035979,39644.51,18691.842719,29.71,470869,...,395945.139837,34070.51,18170.057302,29.71,465350,29.71,465350,618816.138127,31055.34,26929.97
13,서대문구,17.63,319554,17.63,319554,269446.892818,8512.67,34678.011948,17.63,320629,...,278431.294163,5585.37,37179.849433,17.63,318622,17.63,318622,196257.897235,4600.69,36785.895
14,마포구,23.85,375585,23.85,375585,641216.866384,16906.64,43095.613479,23.85,375162,...,534459.275715,15913,44599.54,23.85,372745,23.85,372745,428715.867564,14686.74389,50782.73
15,양천구,17.41,444010,17.41,444010,306956.891847,25391.86,35709.219378,17.41,439252,...,247774.171628,26215.28,31874.292121,17.41,434351,17.41,434351,332819.813945,26045.52,35318.19
16,강서구,41.45,574638,41.45,574638,1712728.080843,32602.32,97085.406573,41.45,568826,...,1742324.756551,17314.88,103307.887801,41.45,562194,41.45,562194,1858065.02663,14562.4,112700.17
17,구로구,20.12,418418,20.12,418418,512911.710709,16082.51,40342.668833,20.12,415651,...,445650.363712,12961.31,41613.685682,20.12,411916,20.12,411916,302408.936536,10003.62,46984.97
18,금천구,13.02,242818,13.02,242818,419382.424161,23364.98,12465.787042,13.02,241105,...,366852.205836,21798.16,12052.897976,13.02,239070,13.02,239070,225589.869329,21685.35,11544.16
19,영등포구,24.55,398085,24.55,398085,825651.235308,13449.86,42533.527228,24.55,397800,...,567118.704423,11152.17,43506.324821,24.55,397173,24.55,397173,593281.322407,8176.7,44895.635
20,동작구,16.36,390432,16.36,390432,391693.962366,13848.39638,28957.641721,16.36,389714,...,412026.240022,10416.33,29037.250577,16.35,387352,16.35,387352,987083.110619,9483.89,29140.36
21,관악구,29.57,501226,29.57,501226,492992.630927,20502.94,33467.806017,29.57,497883,...,401288.120933,18433.98,32878.894852,29.57,495620,29.57,495620,348086.943774,14071.6,26222.78
22,서초구,46.97,408451,46.97,408451,1041662.703339,23526.15,55397.587403,46.97,412078,...,1347743.574729,17252,56119.795993,46.97,413076,46.97,413076,1224794.4087,17004.22,54059.01
23,강남구,39.5,534103,39.5,534103,1364964.091292,26400.147,92695.311804,39.5,550282,...,1260886.113959,23987.28,95511.235919,39.51,563215,39.51,563215,1068333.962557,21239.18,92562.59
24,송파구,33.88,664514,33.88,664514,909950.736867,34028.245,51322.93042,33.88,660025,...,686606.199688,25205.13,52581.728788,33.88,656310,33.88,656310,732026.1621,14974.49,59733.49
25,강동구,24.59,464037,24.59,464037,758299.026145,16586.95,29479.222745,24.59,463318,...,594208.520422,14844.6,30689.062887,24.59,481474,24.59,481474,527475.01825,10794.94,42576.37

In [11]:
save_path = r'C:\8ssible-Healing-Seoul-Analysis\branch_SG\8SSIBLE_SG_DATA\쓰레기수거_현황_정리.csv'

df_trash.to_csv(save_path, index=False, encoding='utf-8-sig')