In [9]:
import pandas as pd
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
import os
import glob
import pandas as pd

def calc_vibration_mean(file_path):
    df = pd.read_csv(file_path, encoding='cp949')

    df['측정시간'] = pd.to_datetime(
        df['측정시간'],
        format='%Y-%m-%d_%H:%M:%S',
        errors='coerce'
    )

    iso = df['측정시간'].dt.isocalendar()
    df['week'] = iso['year'].astype(str) + '-' + iso['week'].astype(str)

    df = df.loc[~df['자치구'].isin(['Seoul_Grand_Park', 'mobile_type'])].copy()

    value_cols = [
        '소음 평균(dB)',
        '진동(x) 평균(mm/s)',
        '진동(y) 평균(mm/s)',
        '진동(z) 평균(mm/s)'
    ]

    for col in value_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    result = (
        df.groupby(['week', '자치구', '지역'])[value_cols]
        .mean()
        .reset_index()
    )

    result['file_name'] = os.path.basename(file_path)

    return result

folder_path = r'C:\8ssible-Healing-Seoul-Analysis\branch_SG\8SSIBLE_SG_DATA\S-DoT_NATURE_2023년(2023.01.01~2024.01.01)'

file_list = sorted(glob.glob(os.path.join(folder_path, 'S-DoT_NATURE_*.csv')))

all_result = pd.concat(
    [calc_vibration_mean(file) for file in file_list],
    ignore_index=True
)

print(all_result)

C:\Users\PC2506\AppData\Local\Temp\ipykernel_29412\4874098.py:6: DtypeWarning: Columns (0: 조도 최대(lux), 1: 소음 최소(dB), 2: 오존 최대(ppm), 3: 오존 평균(ppm), 4: 오존 최소(ppm)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='cp949')
C:\Users\PC2506\AppData\Local\Temp\ipykernel_29412\4874098.py:6: DtypeWarning: Columns (0: 온도 최대(℃), 1: 온도 평균(℃), 2: 온도 최소(℃), 3: 습도 최대(%), 4: 습도 평균(%), 5: 습도 최소(%), 6: 풍속 최대(m/s), 7: 풍속 평균(m/s), 8: 풍속 최소(m/s), 9: 풍향 최대(m/s), 10: 풍향 평균(m/s), 11: 풍향 최소(m/s), 12: 조도 최대(lux), 13: 조도 평균(lux), 14: 조도 최소(lux), 15: 자외선 최대(UV), 16: 자외선 평균(UV), 17: 자외선 최대(UV).1, 18: 소음 최대(dB), 19: 소음 평균(dB), 20: 소음 최소(dB), 21: 진동(x) 최대(mm/s), 22: 진동(x) 평균(mm/s), 23: 진동(x) 최소(mm/s), 24: 진동(y) 최대(mm/s), 25: 진동(y) 평균(mm/s), 26: 진동(y) 최소(mm/s), 27: 진동(z) 최대(mm/s), 28: 진동(z) 평균(mm/s), 29: 진동(z) 최소(mm/s), 30: 흑구온도 최대(℃), 31: 흑구온도 평균(℃), 32: 흑구온도 최소(℃), 33: 이산화질소 최대(ppm), 34: 이산화질소 평균(ppm), 35: 이산화질소 최소(ppm), 36: 일산화탄소 최대(ppm), 37: 일산화탄소 평균(ppm), 38: 일산화탄소 최소(ppm), 39: 이산화황 최대(ppm), 40: 이산화황 평균(ppm), 41: 이산화황 최소(ppm), 42: 암모니아 최대(ppm), 43: 암모니아 평균(ppm), 44: 암모니아 최소(ppm), 45: 황화수소 최대(ppm), 46: 황화수소 평균(ppm), 47: 황화수소 최소(ppm), 48: 오존 최대(ppm), 49: 오존 평균(ppm), 50: 오존 최소(ppm)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='cp949')

         week              자치구                지역  소음 평균(dB)  진동(x) 평균(mm/s)  \
0     2022-52        Dobong-gu   commercial_area  50.782609        4.000000
1     2022-52        Dobong-gu   industrial_area  43.101449        2.782609
2     2022-52        Dobong-gu       main_street  51.000000             NaN
3     2022-52        Dobong-gu  residential_area  47.935652        2.741688
4     2022-52        Dobong-gu   roads_and_parks  52.043478        4.347826
...       ...              ...               ...        ...             ...
6911   2024-1  Yeongdeungpo-gu   roads_and_parks  57.884712        0.022143
6912   2024-1       Yongsan-gu   commercial_area  45.250000        0.030625
6913   2024-1       Yongsan-gu       main_street  55.681250             NaN
6914   2024-1       Yongsan-gu  residential_area  45.207527        0.024088
6915   2024-1       Yongsan-gu   roads_and_parks  54.625000        0.024812

      진동(y) 평균(mm/s)  진동(z) 평균(mm/s)                          file_name
0          13.000000      104.000000        S-DoT_NATURE_2023.01.01.csv
1           6.652174      105.434783        S-DoT_NATURE_2023.01.01.csv
2                NaN             NaN        S-DoT_NATURE_2023.01.01.csv
3           7.439898      102.843990        S-DoT_NATURE_2023.01.01.csv
4           4.239130      105.086957        S-DoT_NATURE_2023.01.01.csv
...              ...             ...                                ...
6911        0.068697        1.056892  S-DoT_NATURE_2024.01.01-01.07.csv
6912        0.036187        1.007687  S-DoT_NATURE_2024.01.01-01.07.csv
6913             NaN             NaN  S-DoT_NATURE_2024.01.01-01.07.csv
6914        0.064745        1.036007  S-DoT_NATURE_2024.01.01-01.07.csv
6915        0.094250        1.020563  S-DoT_NATURE_2024.01.01-01.07.csv

[6916 rows x 8 columns]

In [11]:
all_result

,week,자치구,지역,소음 평균(dB),진동(x) 평균(mm/s),진동(y) 평균(mm/s),진동(z) 평균(mm/s),file_name
0,2022-52,Dobong-gu,commercial_area,50.782609,4.000000,13.000000,104.000000,S-DoT_NATURE_2023.01.01.csv
1,2022-52,Dobong-gu,industrial_area,43.101449,2.782609,6.652174,105.434783,S-DoT_NATURE_2023.01.01.csv
2,2022-52,Dobong-gu,main_street,51.000000,NaN,NaN,NaN,S-DoT_NATURE_2023.01.01.csv
3,2022-52,Dobong-gu,residential_area,47.935652,2.741688,7.439898,102.843990,S-DoT_NATURE_2023.01.01.csv
4,2022-52,Dobong-gu,roads_and_parks,52.043478,4.347826,4.239130,105.086957,S-DoT_NATURE_2023.01.01.csv
...,...,...,...,...,...,...,...,...
6911,2024-1,Yeongdeungpo-gu,roads_and_parks,57.884712,0.022143,0.068697,1.056892,S-DoT_NATURE_2024.01.01-01.07.csv
6912,2024-1,Yongsan-gu,commercial_area,45.250000,0.030625,0.036187,1.007687,S-DoT_NATURE_2024.01.01-01.07.csv
6913,2024-1,Yongsan-gu,main_street,55.681250,NaN,NaN,NaN,S-DoT_NATURE_2024.01.01-01.07.csv
6914,2024-1,Yongsan-gu,residential_area,45.207527,0.024088,0.064745,1.036007,S-DoT_NATURE_2024.01.01-01.07.csv
6915,2024-1,Yongsan-gu,roads_and_parks,54.625000,0.024812,0.094250,1.020563,S-DoT_NATURE_2024.01.01-01.07.csv

In [12]:
all_result = all_result.loc[~all_result['week'].isin(['2022-52', '2024-1'])].copy()

print(all_result['week'].unique())

<StringArray>
[ '2023-1',  '2023-2',  '2023-3',  '2023-4',  '2023-5',  '2023-6',  '2023-7',
  '2023-8',  '2023-9', '2023-10', '2023-11', '2023-12', '2023-13', '2023-14',
 '2023-15', '2023-16', '2023-17', '2023-18', '2023-19', '2023-20', '2023-21',
 '2023-22', '2023-23', '2023-24', '2023-25', '2023-26', '2023-27', '2023-28',
 '2023-29', '2023-30', '2023-31', '2023-32', '2023-33', '2023-34', '2023-35',
 '2023-36', '2023-37', '2023-38', '2023-39', '2023-40', '2023-41', '2023-42',
 '2023-43', '2023-44', '2023-45', '2023-46', '2023-47', '2023-48', '2023-49',
 '2023-50', '2023-51', '2023-52']
Length: 52, dtype: str

In [13]:
col = all_result['진동(x) 평균(mm/s)']

print('전체 개수:', len(col))
print('값 있는 개수:', col.count())
print('결측치 개수:', col.isna().sum())

전체 개수: 6661
값 있는 개수: 5265
결측치 개수: 1396

In [14]:
missing_by_region = (
    all_result.groupby('지역')['진동(x) 평균(mm/s)']
    .agg(
        total_count='size',
        missing_count=lambda x: x.isna().sum()
    )
    .reset_index()
)

missing_by_region['missing_ratio'] = (
    missing_by_region['missing_count'] / missing_by_region['total_count']
)

missing_by_region = missing_by_region.sort_values(
    by='missing_count',
    ascending=False
)

print(missing_by_region.sort_values('total_count', ascending=False).head(10))

                    지역  total_count  missing_count  missing_ratio
5     residential_area         1300              0       0.000000
6      roads_and_parks         1293            120       0.092807
0      commercial_area         1208             81       0.067053
1      industrial_area          936            104       0.111111
7  traditional_markets          780             52       0.066667
2          main_street          728            727       0.998626
3                parks          260            260       1.000000
4    public_facilities          156             52       0.333333

In [15]:
import os
import glob
import pandas as pd

def calc_monthly_mean(file_path):
    df = pd.read_csv(file_path, encoding='cp949')

    df['측정시간'] = pd.to_datetime(
        df['측정시간'],
        format='%Y-%m-%d_%H:%M:%S',
        errors='coerce'
    )

    df = df.dropna(subset=['측정시간']).copy()
    df = df.loc[~df['자치구'].isin(['Seoul_Grand_Park', 'mobile_type'])].copy()

    df['month'] = (
        df['측정시간'].dt.year.astype(str)
        + '.'
        + df['측정시간'].dt.month.astype(str)
    )

    value_cols = [
        '소음 평균(dB)',
        '진동(x) 평균(mm/s)',
        '진동(y) 평균(mm/s)',
        '진동(z) 평균(mm/s)'
    ]

    for col in value_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    result = (
        df.groupby(['month', '자치구', '지역'])[value_cols]
        .mean()
        .reset_index()
    )

    return result

folder_path = r'C:\8ssible-Healing-Seoul-Analysis\branch_SG\8SSIBLE_SG_DATA\S-DoT_NATURE_2023년(2023.01.01~2024.01.01)'
file_list = sorted(glob.glob(os.path.join(folder_path, 'S-DoT_NATURE_*.csv')))

all_result = pd.concat(
    [calc_monthly_mean(file) for file in file_list],
    ignore_index=True
)

all_result = all_result.loc[all_result['month'] != '2024.1'].copy()

C:\Users\PC2506\AppData\Local\Temp\ipykernel_29412\3856599565.py:6: DtypeWarning: Columns (0: 조도 최대(lux), 1: 소음 최소(dB), 2: 오존 최대(ppm), 3: 오존 평균(ppm), 4: 오존 최소(ppm)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='cp949')
C:\Users\PC2506\AppData\Local\Temp\ipykernel_29412\3856599565.py:6: DtypeWarning: Columns (0: 온도 최대(℃), 1: 온도 평균(℃), 2: 온도 최소(℃), 3: 습도 최대(%), 4: 습도 평균(%), 5: 습도 최소(%), 6: 풍속 최대(m/s), 7: 풍속 평균(m/s), 8: 풍속 최소(m/s), 9: 풍향 최대(m/s), 10: 풍향 평균(m/s), 11: 풍향 최소(m/s), 12: 조도 최대(lux), 13: 조도 평균(lux), 14: 조도 최소(lux), 15: 자외선 최대(UV), 16: 자외선 평균(UV), 17: 자외선 최대(UV).1, 18: 소음 최대(dB), 19: 소음 평균(dB), 20: 소음 최소(dB), 21: 진동(x) 최대(mm/s), 22: 진동(x) 평균(mm/s), 23: 진동(x) 최소(mm/s), 24: 진동(y) 최대(mm/s), 25: 진동(y) 평균(mm/s), 26: 진동(y) 최소(mm/s), 27: 진동(z) 최대(mm/s), 28: 진동(z) 평균(mm/s), 29: 진동(z) 최소(mm/s), 30: 흑구온도 최대(℃), 31: 흑구온도 평균(℃), 32: 흑구온도 최소(℃), 33: 이산화질소 최대(ppm), 34: 이산화질소 평균(ppm), 35: 이산화질소 최소(ppm), 36: 일산화탄소 최대(ppm), 37: 일산화탄소 평균(ppm), 38: 일산화탄소 최소(ppm), 39: 이산화황 최대(ppm), 40: 이산화황 평균(ppm), 41: 이산화황 최소(ppm), 42: 암모니아 최대(ppm), 43: 암모니아 평균(ppm), 44: 암모니아 최소(ppm), 45: 황화수소 최대(ppm), 46: 황화수소 평균(ppm), 47: 황화수소 최소(ppm), 48: 오존 최대(ppm), 49: 오존 평균(ppm), 50: 오존 최소(ppm)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='cp949')

In [16]:
all_result

,month,자치구,지역,소음 평균(dB),진동(x) 평균(mm/s),진동(y) 평균(mm/s),진동(z) 평균(mm/s)
0,2023.1,Dobong-gu,commercial_area,50.782609,4.000000,13.000000,104.000000
1,2023.1,Dobong-gu,industrial_area,43.101449,2.782609,6.652174,105.434783
2,2023.1,Dobong-gu,main_street,51.000000,NaN,NaN,NaN
3,2023.1,Dobong-gu,residential_area,47.935652,2.741688,7.439898,102.843990
4,2023.1,Dobong-gu,roads_and_parks,52.043478,4.347826,4.239130,105.086957
...,...,...,...,...,...,...,...
8064,2023.12,Yeongdeungpo-gu,roads_and_parks,56.736842,0.021559,0.067095,1.058183
8065,2023.12,Yongsan-gu,commercial_area,44.233251,0.030000,0.032246,1.009231
8066,2023.12,Yongsan-gu,main_street,52.047146,NaN,NaN,NaN
8067,2023.12,Yongsan-gu,residential_area,44.062383,0.023555,0.064431,1.036955
8068,2023.12,Yongsan-gu,roads_and_parks,53.643921,0.026377,0.097866,1.022457